repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: sort-simple-yaml
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        language: system
        entry: golangci-lint run --fix
        types: [go]
        pass_filenames: false
      - id: go-mod-tidy
        name: go mod tidy
        language: system
        entry: go mod tidy
        types: [go]
        pass_filenames: false
